[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "python-telegram-bot==20.3",
    "telegram>=0.0.1",
]
